title: "Docker Blog: 21BCP110"
description: "Building a Three-Tier Application with Docker"
url: "https://shrutimishra27.github.io"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins:
 - jekyll-sitemap
